
// Code generated by stanc v2.26.1
#include <stan/model/model_header.hpp>
namespace posterior_predictive_log_model_namespace {


inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 

stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 10, column 2 to column 13)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 11, column 2 to column 14)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 12, column 2 to column 16)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 13, column 2 to column 15)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 14, column 2 to column 24)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 18, column 1 to column 14)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 19, column 1 to column 89)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 30, column 2 to line 31, column 51)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 33, column 2 to column 20)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 35, column 4 to column 52)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 34, column 17 to line 36, column 3)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 34, column 2 to line 36, column 3)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 26, column 2 to column 26)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 2, column 2 to column 8)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 3, column 9 to column 10)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 3, column 2 to column 16)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 4, column 9 to column 10)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 4, column 2 to column 26)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 5, column 9 to column 10)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 5, column 2 to column 29)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 6, column 9 to column 10)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 6, column 2 to column 22)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 18, column 8 to column 9)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 30, column 13 to column 14)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/final/stan/posterior_predictive-log.stan', line 33, column 9 to column 10)"};



class posterior_predictive_log_model final : public model_base_crtp<posterior_predictive_log_model> {

 private:
  int n;
  Eigen::Matrix<double, -1, 1> mpg;
  Eigen::Matrix<double, -1, 1> weight_center;
  Eigen::Matrix<double, -1, 1> cylinders_center;
  Eigen::Matrix<double, -1, 1> hp_center;
 
 public:
  ~posterior_predictive_log_model() { }
  
  inline std::string model_name() const final { return "posterior_predictive_log_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1", "stancflags = "};
  }
  
  
  posterior_predictive_log_model(stan::io::var_context& context__,
                                 unsigned int random_seed__ = 0,
                                 std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "posterior_predictive_log_model_namespace::posterior_predictive_log_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 14;
      context__.validate_dims("data initialization","n","int",
          context__.to_vec());
      n = std::numeric_limits<int>::min();
      
      current_statement__ = 14;
      n = context__.vals_i("n")[(1 - 1)];
      current_statement__ = 15;
      validate_non_negative_index("mpg", "n", n);
      current_statement__ = 16;
      context__.validate_dims("data initialization","mpg","double",
          context__.to_vec(n));
      mpg = Eigen::Matrix<double, -1, 1>(n);
      stan::math::fill(mpg, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> mpg_flat__;
        current_statement__ = 16;
        assign(mpg_flat__, nil_index_list(), context__.vals_r("mpg"),
          "assigning variable mpg_flat__");
        current_statement__ = 16;
        pos__ = 1;
        current_statement__ = 16;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 16;
          assign(mpg, cons_list(index_uni(sym1__), nil_index_list()),
            mpg_flat__[(pos__ - 1)], "assigning variable mpg");
          current_statement__ = 16;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 17;
      validate_non_negative_index("weight_center", "n", n);
      current_statement__ = 18;
      context__.validate_dims("data initialization","weight_center","double",
          context__.to_vec(n));
      weight_center = Eigen::Matrix<double, -1, 1>(n);
      stan::math::fill(weight_center, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> weight_center_flat__;
        current_statement__ = 18;
        assign(weight_center_flat__, nil_index_list(),
          context__.vals_r("weight_center"),
          "assigning variable weight_center_flat__");
        current_statement__ = 18;
        pos__ = 1;
        current_statement__ = 18;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 18;
          assign(weight_center,
            cons_list(index_uni(sym1__), nil_index_list()),
            weight_center_flat__[(pos__ - 1)],
            "assigning variable weight_center");
          current_statement__ = 18;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 19;
      validate_non_negative_index("cylinders_center", "n", n);
      current_statement__ = 20;
      context__.validate_dims("data initialization","cylinders_center",
          "double",context__.to_vec(n));
      cylinders_center = Eigen::Matrix<double, -1, 1>(n);
      stan::math::fill(cylinders_center, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> cylinders_center_flat__;
        current_statement__ = 20;
        assign(cylinders_center_flat__, nil_index_list(),
          context__.vals_r("cylinders_center"),
          "assigning variable cylinders_center_flat__");
        current_statement__ = 20;
        pos__ = 1;
        current_statement__ = 20;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 20;
          assign(cylinders_center,
            cons_list(index_uni(sym1__), nil_index_list()),
            cylinders_center_flat__[(pos__ - 1)],
            "assigning variable cylinders_center");
          current_statement__ = 20;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 21;
      validate_non_negative_index("hp_center", "n", n);
      current_statement__ = 22;
      context__.validate_dims("data initialization","hp_center","double",
          context__.to_vec(n));
      hp_center = Eigen::Matrix<double, -1, 1>(n);
      stan::math::fill(hp_center, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> hp_center_flat__;
        current_statement__ = 22;
        assign(hp_center_flat__, nil_index_list(),
          context__.vals_r("hp_center"),
          "assigning variable hp_center_flat__");
        current_statement__ = 22;
        pos__ = 1;
        current_statement__ = 22;
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          current_statement__ = 22;
          assign(hp_center, cons_list(index_uni(sym1__), nil_index_list()),
            hp_center_flat__[(pos__ - 1)], "assigning variable hp_center");
          current_statement__ = 22;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 23;
      validate_non_negative_index("mu", "n", n);
      current_statement__ = 24;
      validate_non_negative_index("y_rep", "n", n);
      current_statement__ = 25;
      validate_non_negative_index("log_lik", "n", n);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "posterior_predictive_log_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      local_scalar_t__ alpha;
      alpha = DUMMY_VAR__;
      
      current_statement__ = 1;
      alpha = in__.scalar();
      local_scalar_t__ beta_w;
      beta_w = DUMMY_VAR__;
      
      current_statement__ = 2;
      beta_w = in__.scalar();
      local_scalar_t__ beta_cyl;
      beta_cyl = DUMMY_VAR__;
      
      current_statement__ = 3;
      beta_cyl = in__.scalar();
      local_scalar_t__ beta_hp;
      beta_hp = DUMMY_VAR__;
      
      current_statement__ = 4;
      beta_hp = in__.scalar();
      local_scalar_t__ sigma;
      sigma = DUMMY_VAR__;
      
      current_statement__ = 5;
      sigma = in__.scalar();
      current_statement__ = 5;
      if (jacobian__) {
        current_statement__ = 5;
        sigma = stan::math::lb_constrain(sigma, 0, lp__);
      } else {
        current_statement__ = 5;
        sigma = stan::math::lb_constrain(sigma, 0);
      }
      Eigen::Matrix<local_scalar_t__, -1, 1> mu;
      mu = Eigen::Matrix<local_scalar_t__, -1, 1>(n);
      stan::math::fill(mu, DUMMY_VAR__);
      
      current_statement__ = 7;
      assign(mu, nil_index_list(),
        add(
          add(add(alpha, multiply(beta_w, weight_center)),
            multiply(beta_cyl, cylinders_center)),
          multiply(beta_hp, hp_center)), "assigning variable mu");
      {
        current_statement__ = 13;
        lp_accum__.add(normal_lpdf<propto__>(mpg, mu, sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "posterior_predictive_log_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      double alpha;
      alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      alpha = in__.scalar();
      double beta_w;
      beta_w = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      beta_w = in__.scalar();
      double beta_cyl;
      beta_cyl = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      beta_cyl = in__.scalar();
      double beta_hp;
      beta_hp = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      beta_hp = in__.scalar();
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      sigma = in__.scalar();
      current_statement__ = 5;
      sigma = stan::math::lb_constrain(sigma, 0);
      Eigen::Matrix<double, -1, 1> mu;
      mu = Eigen::Matrix<double, -1, 1>(n);
      stan::math::fill(mu, std::numeric_limits<double>::quiet_NaN());
      
      vars__.emplace_back(alpha);
      vars__.emplace_back(beta_w);
      vars__.emplace_back(beta_cyl);
      vars__.emplace_back(beta_hp);
      vars__.emplace_back(sigma);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 7;
      assign(mu, nil_index_list(),
        add(
          add(add(alpha, multiply(beta_w, weight_center)),
            multiply(beta_cyl, cylinders_center)),
          multiply(beta_hp, hp_center)), "assigning variable mu");
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
          vars__.emplace_back(mu[(sym1__ - 1)]);}
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      std::vector<double> y_rep;
      y_rep = std::vector<double>(n, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 8;
      assign(y_rep, nil_index_list(),
        normal_rng(
          add(
            add(add(alpha, multiply(beta_w, weight_center)),
              multiply(beta_cyl, cylinders_center)),
            multiply(beta_hp, hp_center)), sigma, base_rng__),
        "assigning variable y_rep");
      Eigen::Matrix<double, -1, 1> log_lik;
      log_lik = Eigen::Matrix<double, -1, 1>(n);
      stan::math::fill(log_lik, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 12;
      for (int j = 1; j <= n; ++j) {
        current_statement__ = 10;
        assign(log_lik, cons_list(index_uni(j), nil_index_list()),
          normal_lpdf<false>(mpg[(j - 1)], mu[(j - 1)], sigma),
          "assigning variable log_lik");}
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        vars__.emplace_back(y_rep[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        vars__.emplace_back(log_lik[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double alpha;
      alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      double beta_w;
      beta_w = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      beta_w = context__.vals_r("beta_w")[(1 - 1)];
      double beta_cyl;
      beta_cyl = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      beta_cyl = context__.vals_r("beta_cyl")[(1 - 1)];
      double beta_hp;
      beta_hp = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      beta_hp = context__.vals_r("beta_hp")[(1 - 1)];
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      double sigma_free__;
      sigma_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      sigma_free__ = stan::math::lb_free(sigma, 0);
      vars__.emplace_back(alpha);
      vars__.emplace_back(beta_w);
      vars__.emplace_back(beta_cyl);
      vars__.emplace_back(beta_hp);
      vars__.emplace_back(sigma_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("alpha");
    names__.emplace_back("beta_w");
    names__.emplace_back("beta_cyl");
    names__.emplace_back("beta_hp");
    names__.emplace_back("sigma");
    names__.emplace_back("mu");
    names__.emplace_back("y_rep");
    names__.emplace_back("log_lik");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "beta_w");
    param_names__.emplace_back(std::string() + "beta_cyl");
    param_names__.emplace_back(std::string() + "beta_hp");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_rep" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "beta_w");
    param_names__.emplace_back(std::string() + "beta_cyl");
    param_names__.emplace_back(std::string() + "beta_hp");
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_rep" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_w\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_cyl\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_hp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" << n << "},\"block\":\"transformed_parameters\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"array\",\"length\":" << n << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" << n << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_w\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_cyl\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_hp\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" << n << "},\"block\":\"transformed_parameters\"},{\"name\":\"y_rep\",\"type\":{\"name\":\"array\",\"length\":" << n << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" << n << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  

    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        

};
}

using stan_model = posterior_predictive_log_model_namespace::posterior_predictive_log_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return posterior_predictive_log_model_namespace::profiles__;
}

#endif


