
// Code generated by stanc v2.26.1
#include <stan/model/model_header.hpp>
namespace generate_data_model_namespace {


inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 

stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 10, column 4 to column 19)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 11, column 4 to column 20)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 13, column 4 to column 19)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 21, column 12 to column 42)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 19, column 16 to column 45)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 17, column 16 to column 44)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 16, column 12 to line 19, column 45)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 15, column 8 to line 21, column 42)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 14, column 19 to line 22, column 5)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 14, column 4 to line 22, column 5)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 26, column 12 to column 39)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 25, column 8 to line 26, column 39)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 28, column 8 to column 59)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 24, column 19 to line 29, column 5)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 24, column 4 to line 29, column 5)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 2, column 4 to column 25)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 3, column 4 to column 25)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 4, column 4 to column 19)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 5, column 4 to column 19)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 6, column 4 to column 43)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 10, column 11 to column 12)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 10, column 14 to column 15)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 11, column 10 to column 11)",
                                                      " (in '/Users/dominikwozniak/study/data_analytics/lab-4/generate_data.stan', line 13, column 11 to column 12)"};



class generate_data_model final : public model_base_crtp<generate_data_model> {

 private:
  int M;
  int N;
  double alpha;
  double sigma;
  double sig_prob;
 
 public:
  ~generate_data_model() { }
  
  inline std::string model_name() const final { return "generate_data_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1", "stancflags = "};
  }
  
  
  generate_data_model(stan::io::var_context& context__,
                      unsigned int random_seed__ = 0,
                      std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "generate_data_model_namespace::generate_data_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 16;
      M = std::numeric_limits<int>::min();
      
      current_statement__ = 16;
      M = 200;
      current_statement__ = 17;
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 17;
      N = 100;
      current_statement__ = 18;
      alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 18;
      alpha = 3;
      current_statement__ = 19;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 19;
      sigma = 1;
      current_statement__ = 20;
      sig_prob = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 20;
      sig_prob = 0.05;
      current_statement__ = 16;
      current_statement__ = 16;
      check_greater_or_equal(function__, "M", M, 0);
      current_statement__ = 17;
      current_statement__ = 17;
      check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 20;
      current_statement__ = 20;
      check_greater_or_equal(function__, "sig_prob", sig_prob, 0);
      current_statement__ = 20;
      current_statement__ = 20;
      check_less_or_equal(function__, "sig_prob", sig_prob, 1);
      current_statement__ = 21;
      validate_non_negative_index("X", "M", M);
      current_statement__ = 22;
      validate_non_negative_index("X", "N", N);
      current_statement__ = 23;
      validate_non_negative_index("y", "N", N);
      current_statement__ = 24;
      validate_non_negative_index("beta", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "generate_data_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "generate_data_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, -1> X;
      X = Eigen::Matrix<double, -1, -1>(M, N);
      stan::math::fill(X, std::numeric_limits<double>::quiet_NaN());
      
      std::vector<double> y;
      y = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 10;
      for (int m = 1; m <= M; ++m) {
        current_statement__ = 8;
        if (bernoulli_rng(sig_prob, base_rng__)) {
          current_statement__ = 7;
          if (bernoulli_rng(0.5, base_rng__)) {
            current_statement__ = 6;
            assign(beta, cons_list(index_uni(m), nil_index_list()),
              normal_rng(10, 1, base_rng__), "assigning variable beta");
          } else {
            current_statement__ = 5;
            assign(beta, cons_list(index_uni(m), nil_index_list()),
              normal_rng(-10, 1, base_rng__), "assigning variable beta");
          }
        } else {
          current_statement__ = 4;
          assign(beta, cons_list(index_uni(m), nil_index_list()),
            normal_rng(0, 0.25, base_rng__), "assigning variable beta");
        }}
      current_statement__ = 15;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 12;
        for (int m = 1; m <= M; ++m) {
          current_statement__ = 11;
          assign(X,
            cons_list(index_uni(m),
              cons_list(index_uni(n), nil_index_list())),
            normal_rng(0, 1, base_rng__), "assigning variable X");}
        current_statement__ = 13;
        assign(y, cons_list(index_uni(n), nil_index_list()),
          normal_rng(
            (multiply(
               transpose(
                 rvalue(X,
                   cons_list(index_min_max(1, M),
                     cons_list(index_uni(n), nil_index_list())), "X")), beta)
              + alpha), sigma, base_rng__), "assigning variable y");}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
          vars__.emplace_back(
            rvalue(X,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "X"));}}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(y[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(beta[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("X");
    names__.emplace_back("y");
    names__.emplace_back("beta");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(M),
                                             static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "X" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "X" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"X\",\"type\":{\"name\":\"matrix\",\"rows\":" << M << ",\"cols\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"y\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"X\",\"type\":{\"name\":\"matrix\",\"rows\":" << M << ",\"cols\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"y\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  

    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        

};
}
using stan_model = generate_data_model_namespace::generate_data_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return generate_data_model_namespace::profiles__;
}

#endif


